# Generated by Django 5.0.6 on 2024-05-25 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='lasr_name',
            new_name='last_name',
        ),
    ]
