# Generated by Django 5.0.6 on 2024-05-25 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_name_category_title_category_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale_exist',
        ),
    ]
